services:
  reservia:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      # - RESERVIA_NO_AUTH=1  # Uncomment to disable auth
    restart: unless-stopped